# Generated by Django 5.0.4 on 2024-04-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='text')),
                ('part', models.CharField(blank=True, choices=[('noun', 'существительное'), ('verb', 'глагол'), ('adjective', 'прилагательное'), ('adverb', 'наречие'), ('preposition', 'предлог'), ('conjunction', 'союз'), ('interjection', 'междометие')], max_length=12, verbose_name='part')),
                ('transcription', models.CharField(blank=True, max_length=50, verbose_name='transcription')),
                ('translation', models.CharField(max_length=50, verbose_name='translation')),
            ],
        ),
    ]
