# Generated by Django 5.0.4 on 2024-05-11 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, unique=True, verbose_name='text')),
                ('part', models.CharField(blank=True, max_length=50, verbose_name='part')),
                ('transcription', models.CharField(blank=True, max_length=50, verbose_name='transcription')),
                ('translation', models.CharField(max_length=50, verbose_name='translation')),
                ('synonym', models.JSONField(blank=True, null=True, verbose_name='synonym')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognize_lvl', models.IntegerField(default=1, verbose_name='recognize_lvl')),
                ('recognize_time', models.IntegerField(verbose_name='recognize_time')),
                ('reproduce_lvl', models.IntegerField(default=1, verbose_name='reproduce_lvl')),
                ('reproduce_time', models.IntegerField(verbose_name='reproduce_time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_related_with_user', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_related_with_word', to='word.word')),
            ],
        ),
    ]
