# Generated by Django 5.0.4 on 2024-04-15 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='time')),
                ('lvl', models.IntegerField(verbose_name='lvl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_related_with_user', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_related_with_word', to='word.word')),
            ],
        ),
    ]
