# Generated by Django 5.0.4 on 2024-05-13 12:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_rename_userwordrelation_userword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userword',
            unique_together={('user', 'word')},
        ),
    ]
