# Generated by Django 5.0.4 on 2024-05-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_userwordrelation_type_alter_userwordrelation_lvl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='synonym',
            field=models.JSONField(blank=True, null=True, verbose_name='synonym'),
        ),
    ]
