# Generated by Django 5.0.4 on 2024-05-15 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_remove_word_part_remove_word_synonym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='word.translation'),
        ),
    ]
