# Generated by Django 5.0.4 on 2024-05-15 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_alter_translation_frequency_alter_translation_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='word.word'),
        ),
    ]
