# Generated by Django 5.0.4 on 2024-05-15 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0008_alter_meaning_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='word.word'),
        ),
    ]
