# Generated by Django 5.0.4 on 2024-05-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0009_alter_synonym_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='gender',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='gender',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
