# Generated by Django 5.0.4 on 2024-05-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0010_alter_synonym_frequency_alter_synonym_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meaning',
            old_name='translation',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='synonym',
            old_name='translation',
            new_name='word',
        ),
    ]
