# Generated by Django 5.0.4 on 2024-05-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0012_alter_userword_user_alter_userword_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
