# Generated by Django 5.0.4 on 2024-06-22 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0013_alter_synonym_gender_alter_translation_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата добавления'),
            preserve_default=False,
        ),
    ]
