# Generated by Django 5.0.4 on 2024-07-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0014_userword_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
