# Generated by Django 5.0.4 on 2024-07-13 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0016_trainingtype_dictionary_training_delete_userword'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='translation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='word.translation'),
            preserve_default=False,
        ),
    ]
