# Generated by Django 5.0.4 on 2024-08-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0019_alter_dictionary_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TrainingType',
        ),
    ]
