# Generated by Django 5.0.4 on 2024-08-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0020_alter_training_type_delete_trainingtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='type',
            new_name='type_id',
        ),
    ]
