# Generated by Django 5.0.4 on 2024-08-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0023_synonym_part_of_speech_translation_part_of_speech_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synonym',
            name='part_of_speech_name',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='part_of_speech_name',
        ),
        migrations.RemoveField(
            model_name='word',
            name='part_of_speech_name',
        ),
    ]
