# Generated by Django 5.0.4 on 2024-08-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0024_remove_synonym_part_of_speech_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='form',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
