# Generated by Django 5.0.4 on 2024-04-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_author_upload_book_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(verbose_name='page-count'),
        ),
    ]
