# Generated by Django 5.0.4 on 2024-04-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_slug_alter_book_author_alter_book_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
