# Generated by Django 5.0.4 on 2024-04-26 16:20

import apps.book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.JSONField(default=apps.book.models.book_default),
        ),
    ]
