# Generated by Django 5.0.4 on 2024-07-11 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_page', models.IntegerField(verbose_name='target page')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_users', to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
