# Generated by Django 5.0.4 on 2024-09-05 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('word', '0025_word_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountPartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('part_of_speech', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='count_part_of_speech', to='word.partofspeech', verbose_name='Part of Speech')),
            ],
        ),
    ]
