# Generated by Django 5.0.4 on 2024-04-17 15:52

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userbookrelation_target_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.JSONField(default=apps.user.models.settings_default),
        ),
    ]
