# Generated by Django 5.0.4 on 2024-04-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated_email',
            field=models.BooleanField(default=False, verbose_name='activated_email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
