# Generated by Django 5.0.4 on 2024-05-15 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_book'),
        ('user', '0007_user_activated_email_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_users', to='book.book'),
        ),
        migrations.AlterField(
            model_name='userbookrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
