# Generated by Django 5.0.4 on 2024-07-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_settings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='dark_theme',
        ),
        migrations.AddField(
            model_name='settings',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная'), ('red', 'Красная'), ('green', 'Зеленая')], default='light', max_length=20),
        ),
    ]
