# Generated by Django 5.0.4 on 2024-07-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_settings_dark_theme_settings_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBookRelation',
        ),
    ]
